import { SIGNUP_FORM_FIELD_KEY } from './frame/signup-frame'

export const SIGNUP_FIELD_NAME = {
    LOGIN: 'login',
    PASSWORD: 'password'
}
export const SIGNUP_FORM_FIELD_NAME = {
    [SIGNUP_FORM_FIELD_KEY.LOGIN]: SIGNUP_FIELD_NAME.LOGIN,
    [SIGNUP_FORM_FIELD_KEY.PASSWORD]: SIGNUP_FIELD_NAME.PASSWORD,
}
export const SIGNUP_ACTION_TYPE = {
    SINGUP_FORM_UPLOAD_PENDING: 'SINGUP_ACTION_TYPE_SINGUP_FORM_UPLOAD_PENDING',
    SINGUP_FORM_UPLOAD_SUCCESS: 'SINGUP_ACTION_TYPE_SINGUP_FORM_UPLOAD_SUCCESS',
    SINGUP_FORM_UPLOAD_ERROR: 'SINGUP_ACTION_TYPE_SINGUP_FORM_UPLOAD_ERROR',
}
export const SIGNUP_DATA_NAME = {
    LOGIN:'login',
    PASSWORD:'password',
}